- name: Interface Ratelimit Experiment
  connection: ssh
  hosts: all
  vars_files: vars.yml
  gather_facts: true

  tasks:
    - name: Determine Capture Interface Driver
      shell: "ethtool -i {{capture_interface}} | awk 'NR == 1 {print $2}'"
      register: capture_interface_driver
      changed_when: false
      become: yes
      when: capture_driver is not defined

    - name: Set Capture Driver Fact
      set_fact:
        capture_driver: "{{capture_interface_driver.stdout_lines[0]}}"
        cacheable: yes
      when: capture_driver is not defined

    - name: Clean Up old Results
      shell: |
          rm -rf {{ sensor_dir }}/*.csv
          rm -rf {{ sensor_dir }}/*.pid
      args:
          warn: false
      become: yes
      
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts
          
    - name: Begin New Test
      include_tasks: interface-ratelimit-recursive.yml

    - name: Done Looping, Store Final Result
      set_fact:
        interface_pps_limit: "{{line_pps_limit|int - target_to_beat|int}}"
        cacheable: yes

    - name: List Variable Final States
      debug:
        msg: "A levels: {{ A_level | to_yaml }} - B levels: {{ B_level | to_yaml }} - C levels: {{ C_level | to_yaml }} - D levels: {{ D_level | to_yaml }} - E levels: {{ E_level | to_yaml }}"

    - name: Final Result
      debug:
        msg: "Interface PPS Limit: {{inteface_pps_limit}}"


