#########################################
############Experiment 1#################

- name: Interface Rate Limit
  connection: ssh
  gather_facts: false
  hosts: all
  vars: #Defaults, override with "-e"
        packet_size_max: "1500"
        packet_size_min: "1500"
        pps_limit: "100000"
        packet_size: "512"
        num_packets: "2000000"
  tasks:
  - name: Determine Capture Interface Driver
    shell: "ethtool -i {{capture_interface}} | awk 'NR == 1 {print $2}'"
    register: capture_interface_driver
    changed_when: false
    become: yes

  - name: Copy Performance Monitor
    copy:
      src: gather_stats.bash
      dest: "{{sensor_dir}}/gather_stats.bash"
      mode: '0755'

  - name: Launch Performance Monitor
    shell: "./gather_stats.bash {{ pps_limit }} -1 {{ capture_interface }} 1"
    args:
      chdir: "{{ sensor_dir }}/"
    register: results_async
    poll: 0
    async: 3600
    become: yes
    changed_when: false

  - name: Generate Traffic
    local_action:
        module: shell
        _raw_params: sudo pkt-gen -i {{ send_interface }} -f tx -n {{ num_packets }} -R {{ pps_limit }} -w 8 -zZ
        warn: false
    register: sender
    tags: generate
    changed_when: false
    async: 240
    poll: 5
    ignore_errors: yes

  - name: Store Generator Stats
    local_action:
        module: shell
        _raw_params: |
            echo "{{pps_limit}} --" >> "{{send_interface}}-to-{{inventory_hostname}}".log
            echo "{{sender.stdout}}" | tail -2 >> "{{send_interface}}-to-{{inventory_hostname}}".log
    ignore_errors: yes

  - debug:
        var: sender.stdout

  - name: Stop Everything
    shell: kill "$(cat gather.pid)"
    args:
      chdir: "{{ sensor_dir }}"
    become: yes

  - name: Wait for Results
    async_status: jid="{{ results_async.ansible_job_id }}"
    become: yes
    register: results
    until: results.finished
    retries: 30
    failed_when: false
    ignore_errors: yes

  - name: Copy Results
    fetch:
      src: "{{sensor_dir}}/{{ inventory_hostname }}-{{capture_interface_driver.stdout_lines[0]}}-ksoftirqd0-results-verbose.csv"
      dest: "results/{{ inventory_hostname }}-{{capture_interface_driver.stdout_lines[0]}}-ksoftirqd0-results-verbose.csv"
      flat: yes
    changed_when: false

  - name: Copy Totals
    fetch:
      src: "{{sensor_dir}}/{{ inventory_hostname }}-{{capture_interface_driver.stdout_lines[0]}}-ksoftirqd0-results.csv"
      dest: "results/{{ inventory_hostname }}-{{capture_interface_driver.stdout_lines[0]}}-ksoftirqd0-results.csv"
      flat: yes
    changed_when: false

  - name: Display Running Results
    debug:
        var: results.stdout
