- name: Interface Ratelimit Experiment
  connection: ssh
  hosts: all
  vars_files: vars.yml
  gather_facts: true

  tasks:
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts #start fresh

    - name: Determine Capture Interface Driver
      shell: "ethtool -i {{capture_interface}} | awk 'NR == 1 {print $2}'"
      register: capture_interface_driver
      changed_when: false
      become: yes
      when: capture_driver is not defined

    - name: Set Capture Driver Fact
      set_fact:
        capture_driver: "{{capture_interface_driver.stdout_lines[0]}}"
        cacheable: yes
      when: capture_driver is not defined

    - name: Record Initial Variable Levels
      set_fact:
        A_levels: "{{A_levels}} + [ '300' ]"
        B_levels: "{{B_levels}} + [ '1000' ]"
        C_levels: "{{C_levels}} + [ '212922' ]"
        D_levels: "{{D_levels}} + [ '0' ]"
        E_levels: "{{E_levels}} + [ '64' ]"

    - name: Clean Up old Results
      shell: |
          rm -rf {{ sensor_dir }}/*.csv
          rm -rf {{ sensor_dir }}/*.pid
      args:
          warn: false
      become: yes

    - name: Begin New Test
      include_tasks: interface-ratelimit-recursive.yml

    - name: Done Looping, Store Final Result Facts
      set_fact:
        interface_pps_limit: "{{line_pps_limit|int - target_to_beat|int}}"
        NAPI_budget_best: "{{ A_levels[-1] }}"
        backlog_best: "{{ B_levels[-1] }}"
        rmem_best: "{{ C_levels[-1] }}"
        rfs_best: "{{ D_levels[-1] }}"
        backlog_weight_best: "{{ E_levels[-1] }}"
        cacheable: yes

    - name: Store Results File
      local_action:
          module: shell
          _raw_params: |
              echo "{{inventory_hostname}} Interface Test Final"\
              > results/"{{inventory_hostname}}"-interface-final.log

              echo "- A levels: {{ A_levels | to_yaml }}\
              - B levels: {{ B_levels | to_yaml }}\
              - C levels: {{ C_levels | to_yaml }}\
              - D levels: {{ D_levels | to_yaml }}\
              - E levels: {{ E_levels | to_yaml }}"\
              >> results/"{{inventory_hostname}}"-interface-final.log

              echo "- NAPI Budget (A): {{ NAPI_budget_best | to_yaml }}\
              - Kernel Backlog (B): {{ backlog_best | to_yaml }}\
              - Socket queue mem (C): {{ rmem_best | to_yaml }}\
              - RFS Table Size (D): {{ rfs_best | to_yaml }}\
              - Backlog poll weight (E): {{ backlog_weight_best | to_yaml }}"\
              >> results/"{{inventory_hostname}}"-interface-final.log

              echo "- Number of Loops: {{ test_counter | to_yaml }}\
              - Factor History: {{ significant_factors_history | to_yaml }}\
              - Loop Bests: {{ last_loop_best_history | to_yaml }}\
              - Interface PPS Limit: {{interface_pps_limit}}"\
               >> results/"{{inventory_hostname}}"-interface-final.log
      ignore_errors: yes


    - name: List Variable States
      debug:
        msg: "
        - A levels: {{ A_levels | to_yaml }}
        - B levels: {{ B_levels | to_yaml }}
        - C levels: {{ C_levels | to_yaml }}
        - D levels: {{ D_levels | to_yaml }}
        - E levels: {{ E_levels | to_yaml }}"

    - name: List Factor History
      debug:
        msg: "
        - Number of Loops: {{ test_counter | to_yaml }}
        - Factor History: {{ significant_factors_history | to_yaml }}"

    - name: Final Optimization Results
      debug:
        msg: "
        - NAPI Budget: {{ NAPI_budget_best | to_yaml }}
        - Kernel Backlog: {{ backlog_best | to_yaml }}
        - Socket queue mem: {{ rmem_best | to_yaml }}
        - RFS Table Size: {{ rfs_best | to_yaml }}
        - Backlog poll weight: {{ backlog_weight_best | to_yaml }}"

    - name: Final Result
      debug:
        msg: "Interface PPS Limit: {{interface_pps_limit}}"
