#########################################
############Experiment 2#################

- name: Kernel Rate Limit
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
        num_packets: "3310426" #Dataset Pcap has this many packets
        pps_limit: "100000" #Default, override with "-e" 
        send_interface: "eth1"
        capture_interface: "eth0"
        #ansible_become_password: !vault |
          #  $ANSIBLE_VAULT;1.1;AES256
          #fix for repo
  tasks:
  - name: Gather pre drop count
    shell: cat /sys/class/net/{{ capture_interface }}/statistics/rx_missed_errors
    register: pre
   
   #disk speed is important here. Flash is almost certainly too slow at fast speeds
   #buffer size is also a variable to tune
  - name: Begin tcpdump
    shell: tcpdump -i {{ capture_interface }} -B 819200 -n -w /media/root/ext/experiment.pcap
    register: tcpdump_async
    become: yes
    poll: 0
    async: 360
    
  - name: Send traffic via tcpreplay
    local_action: 
        module: shell sudo tcpreplay -i {{ send_interface }} --netmap -p {{ pps_limit }} -K ~/cic-ids/useme_capWIN-J6GMIG1DQE5-172.31.67.62_iwasfixed 
        
  - name: Stop tcpdump
    shell: killall tcpdump
    become: yes    
  
  - name: Wait for tcpdump to actually stop
    async_status: jid="{{ tcpdump_async.ansible_job_id }}"
    become: yes
    register: tcpdump_result
    until: tcpdump_result.finished
    retries: 30
    
  - name: Gather post drop count result
    shell: cat /sys/class/net/{{ capture_interface }}/statistics/rx_missed_errors
    register: post
    
  - name: store result locally
    local_action: shell echo "{{pps_limit|int}},{{num_packets|int}},{{post.stdout|int - pre.stdout|int}},{{tcpdump_result.stderr_lines[3] | regex_search('\d+')}}" >> result_ex2


  - debug: msg="Kernel drops {{ tcpdump_result.stderr_lines[3] | regex_search('\d+') }}"
  - debug: msg="Interface drops {{ post.stdout|int - pre.stdout|int }}"
  - debug: msg="PPS Limit- {{ pps_limit }} -- Drop count before test {{ pre.stdout|int }} and after test {{ post.stdout|int }} (diff {{ post.stdout|int - pre.stdout|int }})"