#This playbook acts as the "main" function
#It has to be its own file since the "tasks:" keyword can only appear once 
#within all the files

#Replace %%% with names of variables


- name: Generic Experiment Template
  connection: ssh
  hosts: all
  vars_files: vars.yml
  gather_facts: true

  tasks:
    - name: Clear gathered facts from all currently targeted hosts
      meta: clear_facts #start fresh
  
    - name: Clean Up old Results
      shell: |
          rm -rf "{{ experiment_dir }}"/*.csv
      args:
          warn: false
      become: yes
      
    - name: Record Initial Variable Levels
      set_fact:
        A_levels: "{{A_levels}} + [ '%%%%%' ]"
        B_levels: "{{B_levels}} + [ '%%%%%' ]"
        C_levels: "{{C_levels}} + [ '%%%%%' ]"
        D_levels: "{{D_levels}} + [ '%%%%%' ]"
        E_levels: "{{E_levels}} + [ '%%%%%' ]"      
      
    - name: Begin New Test
      include_tasks: template-benchmark-outerloop.yml

        
   - name: Done Looping, Store Final Result Facts
      set_fact:
        your_result: "{{ %%%%% }}"
        A_best: "{{ A_levels[-1] }}"
        B_best: "{{ B_levels[-1] }}"
        C_best: "{{ C_levels[-1] }}"
        D_best: "{{ D_levels[-1] }}"
        E_best: "{{ E_levels[-1] }}"
        cacheable: yes

    - name: Store Results File
      local_action:
          module: shell
          _raw_params: |
              echo "{{inventory_hostname}}  Test Final"\
              > results/"{{inventory_hostname}}"-testxyz-final.log

              echo "- A levels: {{ A_levels | to_yaml }}\
              - B levels: {{ B_levels | to_yaml }}\
              - C levels: {{ C_levels | to_yaml }}\
              - D levels: {{ D_levels | to_yaml }}\
              - E levels: {{ E_levels | to_yaml }}"\
              >> results/"{{inventory_hostname}}"-testxyz-final.log

              echo "- Best (A): {{ A_best | to_yaml }}\
              - Best (B): {{ B_best | to_yaml }}\
              - Best (C): {{ C_best | to_yaml }}\
              - Best (D): {{ D_best | to_yaml }}\
              - Best (E): {{ E_best | to_yaml }}"\
              >> results/"{{inventory_hostname}}"-testxyz-final.log

              echo "- Number of Loops: {{ test_counter | to_yaml }}\
              - Factor History: {{ significant_factors_history | to_yaml }}\
              - Loop Bests: {{ last_loop_best_history | to_yaml }}\
              - your_result: {{ %%%%% }}"\
               >> results/"{{inventory_hostname}}"-testxyz-final.log
      ignore_errors: yes


    - name: Display Variable States
      debug:
        msg: "
        - A levels: {{ A_levels | to_yaml }}
        - B levels: {{ B_levels | to_yaml }}
        - C levels: {{ C_levels | to_yaml }}
        - D levels: {{ D_levels | to_yaml }}
        - E levels: {{ E_levels | to_yaml }}"

    - name: Display Factor History
      debug:
        msg: "
        - Number of Loops: {{ test_counter | to_yaml }}
        - Factor History: {{ significant_factors_history | to_yaml }}"

    - name: Display Final Optimization Results
      debug:
        msg: "
        - Best (A): {{ A_best | to_yaml }}
        - Best (B): {{ B_best | to_yaml }}
        - Best (C): {{ C_best | to_yaml }}
        - Best (D): {{ D_best | to_yaml }}
        - Best (E): {{ E_best | to_yaml }}"

    - name: Final Result
      debug:
        msg: "Your final score: {{ %%%%% }}"
